---
name: Clothes
version: 4.1.0
main: TungstenVn\Clothes\Clothes
api:
- 3.0.0
author: TungstenVn
commands:
  clo:
    description: Clothes commands
  clothes:
    description: Clothes commands
  cos:
    description: Clothes commands
  cosplays:
    description: Clothes commands
  nanny:
    description: Clothes commands
    permission: nanny.clothes.command
...
