---
name: Clothes
version: 5.0
main: TungstenVn\Clothes\Clothes
api: 3.0.0
mcpe-protocol: [361, 388, 389, 390, 407, 408, 418, 428]
author: TungstenVn
commands:
  clo:
    description: Clothes commands
  clothes:
    description: Clothes commands
  cos:
    description: Clothes commands
  cosplays:
    description: Clothes commands
  nanny:
    description: Clothes commands
    permission: nanny.clothes.command
...
